package com.ajdar.magnetometerrecorder;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.hardware.*;import android.view.*;import android.widget.*;import java.util.*;import java.io.*;import java.nio.charset.*;import java.text.*;

public class PlotV51Activity extends Activity implements SensorEventListener{
 static final int US=20000,CSV_REQ=5201; SensorManager sm; Sensor mag; TextView stat,read; EditText sid,note; Button start,stop,save; P px,py,pz,pa; Handler h=new Handler(Looper.getMainLooper()); boolean rec=false; long t0=-1,last=-1,wall=-1; float bx,by,bz,ba; int acc=SensorManager.SENSOR_STATUS_UNRELIABLE; ArrayList<S> data=new ArrayList<>();
 Runnable tick=new Runnable(){public void run(){update();h.postDelayed(this,500);}};
 public void onCreate(Bundle b){super.onCreate(b);ui();}
 public void onResume(){super.onResume();h.post(tick);} public void onPause(){super.onPause();h.removeCallbacks(tick);if(sm!=null&&!rec)sm.unregisterListener(this);}
 void ui(){ScrollView sv=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(16),dp(16),dp(16));sv.addView(root);TextView title=new TextView(this);title.setText("MAG Recorder v5.2 - Separate Plots + CSV");title.setTextSize(24);root.addView(title);sid=new EditText(this);sid.setHint("Session ID, e.g. S01_rest_supine");sid.setSingleLine(true);root.addView(sid);note=new EditText(this);note.setHint("Notes: phone position, posture, reference device");note.setMinLines(2);root.addView(note);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);start=new Button(this);start.setText("Start");stop=new Button(this);stop.setText("Stop");stop.setEnabled(false);save=new Button(this);save.setText("Save CSV");save.setEnabled(false);row.addView(start,new LinearLayout.LayoutParams(0,-2,1));row.addView(stop,new LinearLayout.LayoutParams(0,-2,1));row.addView(save,new LinearLayout.LayoutParams(0,-2,1));root.addView(row);stat=new TextView(this);stat.setText("Four separate x-y plots + CSV. x-axis=time(s), y-axis=magnetic field(uT).");stat.setTextSize(15);root.addView(stat);read=new TextView(this);read.setTextSize(16);root.addView(read);px=new P(this,"Bx vs time","Bx (uT)",Color.rgb(220,0,0));py=new P(this,"By vs time","By (uT)",Color.rgb(0,150,0));pz=new P(this,"Bz vs time","Bz (uT)",Color.rgb(0,80,220));pa=new P(this,"|B| vs time","|B| (uT)",Color.rgb(130,0,170));root.addView(px,sz());root.addView(py,sz());root.addView(pz,sz());root.addView(pa,sz());TextView inf=new TextView(this);inf.setText("App version: 5.2\nEach signal has its own x-y axis. Press Stop, then Save CSV.");inf.setTextSize(13);root.addView(inf);setContentView(sv);start.setOnClickListener(v->go());stop.setOnClickListener(v->halt());save.setOnClickListener(v->saveCsv());}
 boolean sensor(){if(sm!=null&&mag!=null)return true;sm=(SensorManager)getSystemService(SENSOR_SERVICE);if(sm==null){stat.setText("Sensor service unavailable");return false;}mag=sm.getDefaultSensor(Sensor.TYPE_MAGNETIC_FIELD);if(mag==null)mag=sm.getDefaultSensor(Sensor.TYPE_MAGNETIC_FIELD_UNCALIBRATED);if(mag==null){stat.setText("No magnetometer found");return false;}return true;}
 void go(){if(!sensor())return;data.clear();px.cl();py.cl();pz.cl();pa.cl();t0=-1;last=-1;wall=System.currentTimeMillis();rec=true;start.setEnabled(false);stop.setEnabled(true);save.setEnabled(false);sid.setEnabled(false);note.setEnabled(false);sm.unregisterListener(this);if(!sm.registerListener(this,mag,US)){stat.setText("Could not start magnetometer");halt();return;}stat.setText("Recording four separate x-y plots...");}
 void halt(){rec=false;if(sm!=null)sm.unregisterListener(this);start.setEnabled(true);stop.setEnabled(false);save.setEnabled(data.size()>0);sid.setEnabled(true);note.setEnabled(true);stat.setText("Stopped. Samples: "+data.size()+". Press Save CSV.");}
 public void onSensorChanged(SensorEvent e){if(e==null||e.values==null||e.values.length<3)return;int type=e.sensor.getType();if(type!=Sensor.TYPE_MAGNETIC_FIELD&&type!=Sensor.TYPE_MAGNETIC_FIELD_UNCALIBRATED)return;if(t0<0)t0=e.timestamp;float t=(e.timestamp-t0)/1000000000f;float dt=last>0?(e.timestamp-last)/1000000f:Float.NaN;last=e.timestamp;bx=e.values[0];by=e.values[1];bz=e.values[2];ba=(float)Math.sqrt(bx*bx+by*by+bz*bz);if(rec){data.add(new S(t,e.timestamp,bx,by,bz,ba,acc,dt));px.add(t,bx);py.add(t,by);pz.add(t,bz);pa.add(t,ba);}}
 public void onAccuracyChanged(Sensor s,int a){acc=a;}
 void update(){float dur=t0>=0&&last>t0?(last-t0)/1000000000f:0;float fs=dur>0&&data.size()>1?(data.size()-1)/dur:0;read.setText(String.format(Locale.US,"Bx %.3f uT   By %.3f uT\nBz %.3f uT   |B| %.3f uT\nSamples %d   Duration %.1f s   fs %.1f Hz   Accuracy %s",bx,by,bz,ba,data.size(),dur,fs,at(acc)));}
 void saveCsv(){if(data.isEmpty()){Toast.makeText(this,"No samples to save",Toast.LENGTH_SHORT).show();return;}String id=clean(sid.getText().toString());if(id.length()==0)id="session";String stamp=new SimpleDateFormat("yyyyMMdd_HHmmss",Locale.US).format(new Date(wall>0?wall:System.currentTimeMillis()));Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("text/csv");i.putExtra(Intent.EXTRA_TITLE,"mag_v5_2_"+id+"_"+stamp+".csv");startActivityForResult(i,CSV_REQ);}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==CSV_REQ&&c==RESULT_OK&&d!=null&&d.getData()!=null){try{OutputStream out=getContentResolver().openOutputStream(d.getData());BufferedWriter w=new BufferedWriter(new OutputStreamWriter(out,StandardCharsets.UTF_8));w.write(csvText());w.close();Toast.makeText(this,"CSV saved",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Save failed: "+e.getMessage(),Toast.LENGTH_LONG).show();}}}
 String csvText(){StringBuilder sb=new StringBuilder();sb.append("# app_version,5.2\n# plot_layout,separate_x_y_plots\n# plot_x_axis,time_s\n# plot_y_axis,magnetic_field_uT\n# subject_or_session,").append(csv(sid.getText().toString())).append("\n# notes,").append(csv(note.getText().toString())).append("\n# device,").append(csv(Build.MANUFACTURER+" "+Build.MODEL)).append("\n# android_version,").append(csv(Build.VERSION.RELEASE)).append("\n# requested_sample_period_us,").append(US).append("\n# sample_count,").append(data.size()).append("\n");if(mag!=null)sb.append("# sensor_name,").append(csv(mag.getName())).append("\n# sensor_vendor,").append(csv(mag.getVendor())).append("\n# sensor_resolution_uT,").append(mag.getResolution()).append("\n# sensor_maximum_range_uT,").append(mag.getMaximumRange()).append("\n");sb.append("time_s,sensor_timestamp_ns,system_start_unix_ms,Bx_uT,By_uT,Bz_uT,B_abs_uT,accuracy,dt_ms\n");for(S s:data)sb.append(String.format(Locale.US,"%.9f,%d,%d,%.9f,%.9f,%.9f,%.9f,%d,%.6f\n",s.t,s.ns,wall,s.x,s.y,s.z,s.a,s.acc,s.dt));return sb.toString();}
 String at(int a){if(a==SensorManager.SENSOR_STATUS_ACCURACY_HIGH)return"high";if(a==SensorManager.SENSOR_STATUS_ACCURACY_MEDIUM)return"medium";if(a==SensorManager.SENSOR_STATUS_ACCURACY_LOW)return"low";return"unreliable";} static String clean(String s){return s==null?"":s.trim().replaceAll("[^A-Za-z0-9_.-]+","_");} static String csv(String s){if(s==null)return"";boolean q=s.contains(",")||s.contains("\n")||s.contains("\"");String e=s.replace("\"","\"\"").replace("\r"," ").replace("\n"," ");return q?"\""+e+"\"":e;} int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);} LinearLayout.LayoutParams sz(){return new LinearLayout.LayoutParams(-1,dp(240));}
 static class S{float t,x,y,z,a,dt;long ns;int acc;S(float t,long ns,float x,float y,float z,float a,int acc,float dt){this.t=t;this.ns=ns;this.x=x;this.y=y;this.z=z;this.a=a;this.acc=acc;this.dt=dt;}}
 public static class P extends View{ArrayDeque<float[]>q=new ArrayDeque<>();Paint b=new Paint(1),g=new Paint(1),tx=new Paint(1),ln=new Paint(1);String title,ylab;P(Context c,String t,String y,int col){super(c);title=t;ylab=y;b.setColor(Color.BLACK);b.setStyle(Paint.Style.STROKE);b.setStrokeWidth(2);g.setColor(Color.LTGRAY);tx.setColor(Color.DKGRAY);tx.setTextSize(23);ln.setColor(col);ln.setStrokeWidth(3);setBackgroundColor(Color.WHITE);}void cl(){q.clear();invalidate();}void add(float t,float v){q.add(new float[]{t,v});while(q.size()>700)q.removeFirst();postInvalidateOnAnimation();}protected void onDraw(Canvas c){super.onDraw(c);int w=getWidth(),h=getHeight();float l=72,T=34,r=w-18,bt=h-50;c.drawText(title,l,25,tx);c.drawRect(l,T,r,bt,b);for(int i=1;i<4;i++){float yy=T+i*(bt-T)/4;c.drawLine(l,yy,r,yy,g);}c.drawText(ylab,4,T+18,tx);c.drawText("time (s)",r-95,h-15,tx);if(q.size()<2){c.drawText("Waiting for samples...",l+10,T+44,tx);return;}float t0=q.peekFirst()[0],t1=q.peekLast()[0];if(t1<=t0)t1=t0+1;float mn=Float.POSITIVE_INFINITY,mx=Float.NEGATIVE_INFINITY;for(float[]p:q){mn=Math.min(mn,p[1]);mx=Math.max(mx,p[1]);}if(Math.abs(mx-mn)<1e-6){mn-=1;mx+=1;}float pad=.1f*(mx-mn);mn-=pad;mx+=pad;c.drawText(String.format(Locale.US,"%.1f",mx),4,T+12,tx);c.drawText(String.format(Locale.US,"%.1f",mn),4,bt,tx);c.drawText(String.format(Locale.US,"%.1fs",t0),l,h-15,tx);c.drawText(String.format(Locale.US,"%.1fs",t1),r-65,h-15,tx);Float lx=null,ly=null;for(float[]p:q){float x=l+(r-l)*(p[0]-t0)/(t1-t0);float y=bt-(bt-T)*(p[1]-mn)/(mx-mn);if(lx!=null)c.drawLine(lx,ly,x,y,ln);lx=x;ly=y;}}}
}